name: Bug 反馈
description: 报告可能的异常行为
title: '[BUG] '
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        欢迎来到 Amrita 的 Issue Tracker！请填写以下表格来提交 Bug。
  - type: input
    id: python-version
    attributes:
      label: Python 版本
      description: 可通过 `python --version` 命令查看
      placeholder: "3.12"
    validations:
      required: true
  - type: input
    id: Amrita-version
    attributes:
      label: Amrita 版本
      description: 使用`pip show amrita_core`查看
      placeholder: 0.1.0
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: 发生了什么?
      description: 填写你认为的 Amrita 的不正常行为
    validations:
      required: true
  - type: textarea
    id: how-reproduce
    attributes:
      label: 如何复现
      description: 填写应当如何操作才能触发这个不正常行为
      placeholder: |
        1. xxx
        2. xxx
        3. xxx
    validations:
      required: true
  - type: textarea
    id: what-expected
    attributes:
      label: 期望的结果?
      description: 填写你认为 Amrita 应当执行的正常行为
    validations:
      required: true
  - type: textarea
    id: Amrita-log
    attributes:
      label: Amrita 运行日志
      description: 请粘贴Amrita运行后报错的控制台内容到此
      render: shell